### ISSUE TITLE
Very low GPU utilization

### ISSUE THREAD

**Issue by SuLvXiangXin** [Riga2/TensoSDF#1]
Thank you for your wonderful work! But I have a little confusion about the training speed.

In the paper, it said 4 hours + 1.5 hours on RTX4090. However, I test the compressor scene on RTX A6000. For the first geometry stage, it takes 8+ hours to complete the training (18w iters), and the GPU utilization is only about 50%. For the next material stage, it takes also about 8 hours to complete the training (10w iters), and the GPU utilization is only about 15%, which I think mainly due to the data preparation in every iteration.

**Comment by Riga2** [comment]
> Thank you for your wonderful work! But I have a little confusion about the training speed.
> 
> In the paper, it said 4 hours + 1.5 hours on RTX4090. However, I test the compressor scene on RTX A6000. For the first geometry stage, it takes 8+ hours to complete the training (18w iters), and the GPU utilization is only about 50%. For the next material stage, it takes also about 8 hours to complete the training (10w iters), and the GPU utilization is only about 15%, which I think mainly due to the data preparation in every iteration.

Hi, sorry for the late reply. Thanks for your interests on our project!
I have tested the compressor scene again on my RTX 4090.

The training time and GPU utilization on the geometry stage are shown below.
![shape_training_time](https://github.com/user-attachments/assets/b6e84f54-3d76-47d2-aa54-7ad9b0096c7a)
![shape_training](https://github.com/user-attachments/assets/b00fb67d-e1ac-4dec-a24d-290ff01326d9)
It seems normal on my machine. The GPU utilization is around 85-90%.

And the training time and GPU utilization on the material stage are shown below.
![mat_training_time](https://github.com/user-attachments/assets/961b7468-519f-4170-a48d-7414c24fc699)
![mat_training](https://github.com/user-attachments/assets/247761f4-071f-4830-ace6-e91f290a9f79)
The GPU utilization is around 35-40%, but the training time is still around 1.5 hrs.

Hope it can help you!

**Comment by SuLvXiangXin** [comment]
Thanks for your reply!
