### ISSUE TITLE
Try on Dynamic Human avatar

### ISSUE THREAD

**Issue by Jiatttliu** [Riga2/TensoSDF#4]
Hi, wonderful work!
Have you try TensoSDF on Dynamic Human avatar? In this task, the transformation of the sampling points needs to be involved.

**Comment by Riga2** [comment]
> Hi, wonderful work! Have you try TensoSDF on Dynamic Human avatar? In this task, the transformation of the sampling points needs to be involved.

Thanks for your interests! 

Currently we have no plan to apply it on Dynamic Human Avatar, but I think it would be interesting. If you have any idea, don't hesitate to try it.

**Comment by Jiatttliu** [comment]
Thanks for your reply! I am working for it now:>
