### ISSUE TITLE
Training on NeILF++ Real Dataset

### ISSUE THREAD

**Issue by YaoanGao** [Riga2/TensoSDF#7]
Thanks for sharing your great work

In the paper, you mentioned that you evaluated the method on real dataset from NeILF++
I downloaded the dataset from [NeILF Dataset](https://apple.ent.box.com/s/2ulz3kjtca53aj3qlwjwyv27zfuug2x5)
But I found that their data format is quite different from the one you assumed in the dataloader, CustomDatabase class (If I m not mistaken)

Could you possibly provide the dataloader for tha raw format of the dataset?
Or the script to transform it into your assumed format
Thx

**Comment by Riga2** [comment]
> Thanks for sharing your great work
> 
> In the paper, you mentioned that you evaluated the method on real dataset from NeILF++ I downloaded the dataset from [NeILF Dataset](https://apple.ent.box.com/s/2ulz3kjtca53aj3qlwjwyv27zfuug2x5) But I found that their data format is quite different from the one you assumed in the dataloader, CustomDatabase class (If I m not mistaken)
> 
> Could you possibly provide the dataloader for tha raw format of the dataset? Or the script to transform it into your assumed format Thx

Hi, thanks for your interests!

We first converted the HDR dataset to LDR images, and then used the [method](https://github.com/liuyuan-pal/NeRO/blob/main/custom_object.md) provided by NeRO to estimate the camera parameters.

**Comment by YaoanGao** [comment]
I will be appreciated if you could share the converted dataset so we can reproduce the experiment.
I am not sure whether this meets the licence requirement of NeILF++ Dataset.

**Comment by Riga2** [comment]
> I will be appreciated if you could share the converted dataset so we can reproduce the experiment. I am not sure whether this meets the licence requirement of NeILF++ Dataset.

Hi, this is the [processed NeILF++ dataset](https://drive.google.com/file/d/1jc0bcMJ-Ygn9sAs_OOQffEwiEUmltNcP/view?usp=drive_link) we used, and we also provide our cropped mesh results, which are used for material estimation.

Hope it helps.

**Comment by YaoanGao** [comment]
It really helped
Thanks so much
